/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const bitnet_linear_f32: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number) => [number, number, number, number];
export const __wbg_bitnetlinearhandle_free: (a: number, b: number) => void;
export const __wbg_decoderlayerhandle_free: (a: number, b: number) => void;
export const decoderlayerhandle_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number, u: number, v: number, w: number, x: number, y: number, z: number, a1: number, b1: number, c1: number, d1: number, e1: number, f1: number, g1: number, h1: number) => number;
export const decoderlayerhandle_self_len: (a: number) => number;
export const decoderlayerhandle_clone_cache: (a: number) => number;
export const decoderlayerhandle_next: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const bitnetlinearhandle_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number) => [number, number, number];
export const bitnetlinearhandle_run: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const __wbg_tokensample_free: (a: number, b: number) => void;
export const tokensample_token_id: (a: number) => number;
export const tokensample_probability: (a: number) => number;
export const tokensample_top_probability: (a: number) => number;
export const tokensample_rank: (a: number) => number;
export const bitnet_sample_token_f32: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number) => [number, number, number];
export const bitnet_linear2_f32: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const bitnet_linear3_f32: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const bitnet_mlp_f32: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
export const layer_norm_f32: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number, number, number];
export const attention_f32: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number) => [number, number, number, number];
export const __wbg_attentionkvcache_free: (a: number, b: number) => void;
export const attentionkvcache_new: (a: number, b: number) => number;
export const attentionkvcache_len: (a: number) => number;
export const attentionkvcache_clear: (a: number) => void;
export const attentionkvcache_clone_cache: (a: number) => number;
export const attentionkvcache_set_cross: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const attentionkvcache_append_self_attention: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number, number, number];
export const attentionkvcache_attention: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const activate_f32: (a: number, b: number, c: number, d: number) => [number, number];
export const gated_activation_f32: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
